title: Lei Yang
description: Stay hungry, stay foolish.
shortbio: Incoming Ph.D. student at MIT EECS.

pgp-pubkey: 2D3EB894C40AE453
pgp-pubkey-link: https://keybase.io/yangl1996/pgp_keys.asc?fingerprint=233a3c408f6e5d3fcc13802f2d3eb894c40ae453

google_analytics: UA-24864834-6
#logo: /static/logo.png

url: http://www.mit.edu
baseurl: "/~leiy"

exclude: ["README.md", "Gemfile", "Gemfile.lock"]

