title: Lei Yang
description: Stay hungry, stay foolish.

google_analytics: UA-24864834-6
#logo: /static/logo.png

url: http://www.mit.edu
baseurl: "/~leiy"

exclude: ["README.md", "Gemfile", "Gemfile.lock"]

